# Generated by Django 3.2.8 on 2021-10-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='users',
            new_name='submissions',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='repo',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
