# Generated by Django 3.2.8 on 2021-10-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20211027_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
